spring.application.name=migration-shim
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/migration
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb://localhost:27017/mydb
